### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by aleeessio** [nanometer5088/CLI-TikTok#5]
OS: Linux, Ubuntu, latest version with all needed packages. Here's the error:

```
How many videos do you want to see? 1

Obtaining URLs - this can take a while when requesting many posts.
Traceback (most recent call last):
  File "/cli/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/cli/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/cli/lib/python3.12/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cli/lib/python3.12/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/cli/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cli/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/usr/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'proxitok.esmailelbob.xyz'. (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cli/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/cli/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'proxitok.esmailelbob.xyz'. (_ssl.c:1000)
```

**Comment by ovosimpatico** [comment]
I appreciate your interest in the software, but TikTok-CLI isn't working anymore, due to issues on [Proxitok](https://github.com/pablouser1/ProxiTok), which was our main data source.

About your issue, seems like `https://proxitok.esmailelbob.xyz` (the Proxitok instance we connected to) is now redirecting to a song, likely the maintainer went rogue or got hacked.

I'll edit the README to inform users about the current state of the project. Unfortunately, I don't plan to further work on TikTok-CLI, and the project will be discontinued.

**Comment by ovosimpatico** [comment]
Deprecation Notice https://github.com/ovosimpatico/CLI-TikTok/commit/3b117944eeee458e6cda8f43b5b33d68f2fd8349
